@startuml "Catena Class Hierarchy"
/' PlantUML image for Catena class hierarcy
'/
namespace McciCatena {

abstract class CatenaBase {
  +struct EUI64_buffer_t;
  +struct EUI64_string_t;
  +struct UniqueID_buffer_t[];
  +struct UniqueID_string_t[];
  +enum OPERATING_FLAGS;
  +enum PLATFORM_FLAGS;
  +{static}uint32_t PlatformFlags_GetModNumber();
  +{static}bool constexpr PlatformFlags+_IsModded();
  +void SafePrintf();
  +const EUI64_Buffer_t *GetSysEUI();
  +{abstract}const CATENA_PLATFORM *GetPlatformForID();
  +{abstract}void GetUniqueID();
  +char *GetUniqueIDstring();
  +const CATENA_PLATFORM *GetPlatform();
  +uint32_t GetOperatingFlags();
  +void SetOperatingFlags();
  +uint32_t GetPlatformFlags();
  +{abstract}void begin();
  +{abstract}const char * CatenaName() const;
  +{abstract}void Sleep();
  +{abstract}cFram *getFram();
  +void poll();
  +void registerObject();
  +addCommands();
  +ProvisioningStyle GetProvisioningStyle();
  +bool GetAbpProvisioningInfo();
  +bool GetOtaaProvisioningInfo();
  +void NetSaveFCntUp();
  +void NetSaveFCntDown();
  +void NetSaveSessionInfo();
  +bool addLoRaWanCommands();
  +{static}CatenaBase *pCatenaBase;
  #{abstract}void registerCommands();
  #{abstract}void getPlatformTable();
  #{abstract}void getCpuIdPlatformTable();
  #cSerialReady	m_SerialReady;
  #EUI64_buffer_t m_SysEUI;
  #cPollingEngine m_PollingEnging;
  #cStreamInlineCollector m_Collector;
  #cCommandStream m_CommandStream;
  -uint32_t m_OperatingFlags;
  -const CATENA_PLATFORM *m_pPlatform;
  -void savePlatform();
  -void getPlatformForCpuId();
}

abstract class CatenaSamd21 {
  +{abstract} bool begin();
  +bool begin(uint32_t overrideMask);
  +book begin(uint32_t uClearMask, uint32_t uSetMask);
  +void GetUniqueID();
  +void Sleep();
  #{abstract}void registerCommands();
  -CatenaRTC m_Rtc;
}

abstract class CatenaStm32 {
  +{abstract} bool begin();
  +bool begin(uint32_t overrideMask);
  +book begin(uint32_t uClearMask, uint32_t uSetMask);
  +void GetUniqueID();
  #{abstract}void registerCommands();
}

abstract class CatenaFeatherM0 {
  +enum ANALOG_PINS;
  +enum DIGITAL_PINS;
  +bool begin();
  +float ReadVbat() const;
  #{abstract}const ProvisioningInfo *GetProvisioningInfo();
  #{abstract}const ProvisioningTable *GetLoRaWANkeys();
}

abstract class CatenaWingFram2k {
  +enum ANALOG_PINS;
  +enum DIGITAL_PINS;
  +bool begin();
  +float ReadVbat() const;
  +cFram *getFram();
  +bool getBootCount(&bootCount);
  #void registerCommands();
  -cFram2k  m_Fram;
  -uint32_t m_BootCount;
}

abstract class CatenaStm32L0 {
  +bool begin();
  +cFram *getFram();
  +bool getBootCount(&bootCount);
  +{abstract}float ReadVbat() const;
  +{abstract}float ReadVbus() const;
  +void Sleep();
  #void registerCommands();
  -cFram8k  m_Fram;
  -uint32_t m_BootCount;
  -CatenaStm32L0Rtc m_Rtc;
}

abstract class Catena455x {
  +enum ANALOG_PINS;
  +enum DIGITAL_PINS;
  +bool begin();
  +float ReadVbat() const;
  +float ReadVbus() const;
}

abstract class Catena461x {
  +enum ANALOG_PINS;
  +enum DIGITAL_PINS;
  +bool begin();
  +float ReadVbat() const;
  +float ReadVbus() const;
}

abstract class Catena480x {
  +enum ANALOG_PINS;
  +enum DIGITAL_PINS;
  +bool begin();
  +float ReadVbat() const;
  +float ReadVbus() const;
}

class Catena4410 {
  +enum DIGITAL_PINS;
  +const char *CatenaName() const;
  #const ProvisioningTable *GetLoRaWANkeys();
  #void getCpuIdPlatformTable();
  -{static}const ProvisioningTable gk_LoRaWAN_Keys;
  -{static}const CPUID_PLATFORM_MAP vCpuIdToPlatform[];
  -{static}const size_t nvCpuIdToPlatform;
}

class Catena4420 {
  +enum DIGITAL_PINS;
  +const char *CatenaName() const;
  #const ProvisioningTable *GetLoRaWANkeys();
  #void getCpuIdPlatformTable();
  -{static}const ProvisioningTable gk_LoRaWAN_Keys;
  -{static}const CPUID_PLATFORM_MAP vCpuIdToPlatform[];
  -{static}const size_t nvCpuIdToPlatform;
}

class Catena4450 {
  +const char *CatenaName() const;
  #void getPlatformTable();
  #void getCpuIdPlatformTable();
  -{static}const CATENA_PLATFORM(* const vPlatforms[]);
  -{static}const size_t nvPlatforms;
  -{static}const CPUID_PLATFORM_MAP vCpuIdToPlatform[];
  -{static}const size_t nvCpuIdToPlatform;
}

class Catena4460 {
  +const char *CatenaName() const;
  #void getPlatformTable();
  -{static}const CATENA_PLATFORM(* const vPlatforms[]);
  -{static}const size_t nvPlatforms;
}

class Catena4470 {
  +const char *CatenaName() const;
  #void getPlatformTable();
  -{static}const CATENA_PLATFORM(* const vPlatforms[]);
  -{static}const size_t nvPlatforms;
}

class Catena4551 {
  +const char *CatenaName() const;
  -{static}const CATENA_PLATFORM(* const vPlatforms[]);
  -{static}const size_t nvPlatforms;
}

class Catena4610 {
  +const char *CatenaName() const;
  #void getPlatformTable();
  -{static}const CATENA_PLATFORM(* const vPlatforms[]);
  -{static}const size_t nvPlatforms;
}

class Catena4611 {
  +const char *CatenaName() const;
  #void getPlatformTable();
  -{static}const CATENA_PLATFORM(* const vPlatforms[]);
  -{static}const size_t nvPlatforms;
}

class Catena4612 {
  +const char *CatenaName() const;
  #void getPlatformTable();
  -{static}const CATENA_PLATFORM(* const vPlatforms[]);
  -{static}const size_t nvPlatforms;
}

class Catena4801 {
  +const char *CatenaName() const;
  #void getPlatformTable();
  -{static}const CATENA_PLATFORM(* const vPlatforms[]);
  -{static}const size_t nvPlatforms;
}

CatenaBase <|-- CatenaSamd21
CatenaBase <|-- CatenaStm32

CatenaSamd21 <|-- CatenaFeatherM0
CatenaSamd21 <|-- CatenaWingFram2k
CatenaFeatherM0 <|-- Catena4410
CatenaFeatherM0 <|-- Catena4420
CatenaWingFram2k <|-- Catena4450
CatenaWingFram2k <|-- Catena4460
CatenaWingFram2k <|-- Catena4470

CatenaStm32 <|-- CatenaStm32L0
CatenaStm32L0 <|-- Catena455x
CatenaStm32L0 <|-- Catena461x
CatenaStm32L0 <|-- Catena480x

Catena455x <|-- Catena4551
Catena461x <|-- Catena4610
Catena461x <|-- Catena4611
Catena461x <|-- Catena4612
Catena480x <|-- Catena4801
}
@enduml